### ISSUE TITLE
ResultsListComponent & co.

### ISSUE THREAD

**Issue by chimo** [chimo/cised-web-directory#1]
Hey @nsieber 

When you get a chance, can you push the "ResultsListComponent"-related files.
Looks like they didn't make it to the repo, somehow.

Thanks!

**Comment by nsieber** [comment]
Done.

**Comment by chimo** [comment]
Sounds good :) 

Make sure you `git add` the untracked files, turns out `git commit -am` only stages modified and deleted files, but not new ones

**Comment by chimo** [comment]
:+1:
